[package]
name = "pdb-dumper"
version = "0.1.0"
authors = ["Camden Smallwood <camden.smallwood@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
opt-level = "s"

[dependencies]
pdb = "0.7"
structopt = { version = "0.3", default-features = false }
